PUT http://localhost:3333/api/games/lock
Content-Type: application/json

{
  "displayName": "testiname",
  "email": "test@email.com",
  "reservationId": "406235a1-b7cd-4ded-872e-c1b2bffb7864",
  "gameId": "6048e84e7987be691c4ccc9e"
}