POST http://localhost:3333/api/users
Content-Type: application/json

{
  "username": "username1232",
  "password": "password",
  "email": "email1s5",
  "firstName": "first",
  "lastName": "last",
  "birthYear": "1922"
}