name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: ["master"]
    types:
      - completed

jobs:
  deploy-backend:
    name: Deploy project to VPS
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: ls
